index:
    path: /
    controller: App\Controller\MainController::index



login:
    path: /login/
    controller: App\Controller\AccountController::login
register:
    path: /register/{enrollment_hash}
    controller: App\Controller\AccountController::register
    defaults:
        enrollment_hash: "none"
profile:
    path: /profile/
    controller: App\Controller\AccountController::profile


block_img:
    path: /block_image{name}
    controller: App\Controller\AdminController::showImage


admin:
    path: /admin/
    controller: App\Controller\AdminController::content
admin_block:
    path: /admin/block
    controller: App\Controller\AdminController::content
admin_block_delete:
    path: /admin/block_delete{block_id}
    controller: App\Controller\AdminController::block_delete
admin_group:
    path: /admin/group
    controller: App\Controller\AdminController::group
    defaults:   { message: null }
admin_group_delete:
    path: /admin/group_delete{group_id}
    controller: App\Controller\AdminController::group_delete
admin_enrollments:
    path: /admin/enrollments
    controller: App\Controller\AdminController::enrollments
admin_user:
    path: /admin/user
    controller: App\Controller\AdminController::user



messages_inbox:
    path: /messages/inbox
    controller: App\Controller\MessagesController::inbox
message:
    path: /message/{message_id}
    controller: App\Controller\MessagesController::display_message
messages_new:
    path: /messages/new
    controller: App\Controller\MessagesController::new_message
messages_sent:
    path: /messages/sent
    controller: App\Controller\MessagesController::sent
messages_drafts:
    path: /messages/drafts
    controller: App\Controller\MessagesController::drafts
attachment_download:
    path: /messages/attachments/{message_id}-{attachment_id}
    controller: App\Controller\MessagesController::download_attachment



logout:
    path: /logout


