index:
    path: /
    controller: App\Controller\MainController::index
contact:
    path: /contact/
    controller: App\Controller\MainController::contact



login:
    path: /login/
    controller: App\Controller\AccountController::login
register:
    path: /register/{enrollment_hash}
    controller: App\Controller\AccountController::register
    defaults:
        enrollment_hash: "none"

profile:
    path: /profile/
    controller: App\Controller\AccountController::profile
profile_family:
    path: /profile/family
    controller: App\Controller\AccountController::family
profile_add_child:
    path: /profile/family/add_child
    controller: App\Controller\AccountController::add_child
profile_add_caretaker:
    path: /profile/family/add_caretaker
    controller: App\Controller\AccountController::add_caretacker


block_img:
    path: /block_image{name}
    controller: App\Controller\AdminController::showImage


admin:
    path: /admin/
    controller: App\Controller\AdminController::content
admin_block:
    path: /admin/block
    controller: App\Controller\AdminController::content
admin_block_edit:
    path: /admin/block/{block_id}
    controller: App\Controller\AdminController::content
admin_block_delete:
    path: /admin/block_delete/{block_id}
    controller: App\Controller\AdminController::block_delete
admin_group:
    path: /admin/group
    controller: App\Controller\AdminController::group
    defaults:   { message: null }
admin_group_delete:
    path: /admin/group_delete/{group_id}
    controller: App\Controller\AdminController::group_delete
admin_enrollments:
    path: /admin/enrollments
    controller: App\Controller\AdminController::enrollments
admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::users
admin_user_disable:
    path: /admin/user_disable/{user_id}
    controller: App\Controller\AdminController::user_disable
admin_user_enable:
    path: /admin/user_enable/{user_id}
    controller: App\Controller\AdminController::user_enable
admin_user_delete:
    path: /admin/user_delete/{user_id}
    controller: App\Controller\AdminController::user_delete
admin_children:
    path: /admin/children
    controller: App\Controller\AdminController::children



messages_inbox:
    path: /messages/inbox
    controller: App\Controller\MessagesController::inbox
message:
    path: /message/{message_id}
    controller: App\Controller\MessagesController::display_message
messages_new:
    path: /messages/new
    controller: App\Controller\MessagesController::new_message
messages_sent:
    path: /messages/sent
    controller: App\Controller\MessagesController::sent
messages_drafts:
    path: /messages/drafts
    controller: App\Controller\MessagesController::drafts
attachment_download:
    path: /messages/attachments/{message_id}-{attachment_id}
    controller: App\Controller\MessagesController::download_attachment



logout:
    path: /logout


