index:
    path: /
    controller: App\Controller\MainController::index
login:
    path: /login/
    controller: App\Controller\AccountController::login
register:
    path: /register/
    controller: App\Controller\AccountController::register
profile:
    path: /profile/
    controller: App\Controller\AccountController::profile
adminpanel:
    path: /admin/
    controller: App\Controller\AdminController::panel
messages:
    path: /messages/
    controller: App\Controller\MessagesController::inbox
logout:
    path: /logout


